### ISSUE TITLE
When running spidy -url http://www.wildlifejunkie.com -w 100, spidy hangs after certain time

### ISSUE THREAD

**Issue by egonzo** [ardanlabs/spidy#7]
It reads allot of the urls but then at some point it hangs and never returns.

Seems like the waitgroup is still waiting for something.

**Comment by influx6** [comment]
Alright, will resolve it asap

**Comment by influx6** [comment]
This got resolved in PR #9 and commit 7a02321d780141948540c72094e4c18bef55fc4c

**Comment by influx6** [comment]
I have verified that spidy runs till the end of crawling the page without any halts after a few changes to the way `farmlinks` works.
