### ISSUE TITLE
Head Requests times out on slow responses

### ISSUE THREAD

**Issue by egonzo** [ardanlabs/spidy#8]
Maybe we can make the HEAD request timeout value a command line parameter. If it is not provided default it to 10 seconds. 

<img width="1253" alt="screenshot at apr 21 11-21-03" src="https://cloud.githubusercontent.com/assets/1641719/14714645/c407e2c2-07b3-11e6-8872-d7ac9fdeecd7.png">

**Comment by influx6** [comment]
Alright

**Comment by influx6** [comment]
This got resolved in PR #9 and commit 7a02321d780141948540c72094e4c18bef55fc4c
